FROM golang:1.27-alpine

RUN apk add --no-cache git ca-certificates

RUN update-ca-certificates

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
